spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tinc
    username: tinc
    password: tinc

  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

application:
  security:
    jwt:
      secret-key: 4671724c237221732252205628715e443c372a4a382746203c4c6b4724632764
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days